# Generated by Django 3.1.4 on 2020-12-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Photo',
            new_name='photo',
        ),
    ]
