# Generated by Django 3.1.4 on 2020-12-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201215_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofolder',
            name='photos',
            field=models.ManyToManyField(null=True, to='home.Photo'),
        ),
    ]
