# Generated by Django 3.1.4 on 2020-12-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201215_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofolder',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
